### ISSUE TITLE
command line flags missing

### ISSUE THREAD

**Issue by leoheck** [AppImageCommunity/AppImageUpdate#218]
There is no --help -h or anthing. Is it possible to add some flags for the command line so we can run it from the terminal without interaction?

**Comment by leoheck** [comment]
![image](https://user-images.githubusercontent.com/1277920/211895078-5eff0785-90d4-44ae-9c3b-4ad046d2da23.png)

**Comment by leoheck** [comment]
For instance, it could have a flag to close the window after the operation.

It could also return the status (success or fail) to the command line. 
It could also have an argument to replace the existing AppImage or to keep it. 
It could also have an argument to run exclusively on the command line, without launching any GUI.

![image](https://user-images.githubusercontent.com/1277920/212113376-cb344046-d3ba-48f1-9359-fa551a671f45.png)

**Comment by leoheck** [comment]
It could also have the option to upgrade all AppImages from the directory path given.

**Comment by leoheck** [comment]
Ah, I figured out that command line flags are already implemented.

![image](https://user-images.githubusercontent.com/1277920/212114597-977d7552-1508-47ee-b914-e3be262616bd.png)

For some reason, they are not working. This is from the main branch.

**Comment by leoheck** [comment]
There is something nasty happening. 

I upgrade the tool using the tool, then it uses the tool name with lowercase characters, and the help is working.

AppImageUpdate-x86_64.AppImage.zs-old  -> appimagetool-x86_64.AppImage             

However the main branch shows the version can be obtained with -V (uppercase V) but this is not working, only the lowercase -v. 

```
~/Applications …
➜ ./appimagetool-x86_64.AppImage --help
Usage:
  appimagetool [OPTION?] SOURCE [DESTINATION] - Generate, extract, and inspect AppImages

Help Options:
  -h, --help                  Show help options

Application Options:
  -l, --list                  List files in SOURCE AppImage
  -u, --updateinformation     Embed update information STRING; if zsyncmake is installed, generate zsync file
  -g, --guess                 Guess update information based on Travis CI or GitLab environment variables
  --bintray-user              Bintray user name
  --bintray-repo              Bintray repository
  --version                   Show version number
  -v, --verbose               Produce verbose output
  -s, --sign                  Sign with gpg[2]
  --comp                      Squashfs compression
  --mksquashfs-opt            Argument to pass through to mksquashfs; can be specified multiple times
  -n, --no-appstream          Do not check AppStream metadata
  --exclude-file              Uses given file as exclude file for mksquashfs, in addition to .appimageignore.
  --runtime-file              Runtime file to use
  --sign-key                  Key ID to use for gpg[2] signatures


~/Applications …
➜ ./appimagetool-x86_64.AppImage -v    
appimagetool, continuous build (commit b719a7f), build <local dev build> built on 2022-09-29 13:55:16 UTC
SOURCE is missing

~/Applications …
➜ ./appimagetool-x86_64.AppImage -V
Option parsing failed: Unknown option -V

~/Applications …
➜ ./appimagetool-x86_64.AppImage --version
appimagetool, continuous build (commit b719a7f), build <local dev build> built on 2022-09-29 13:55:16 UTC

~/Applications …
➜ ./appimagetool-x86_64.AppImage -v       
appimagetool, continuous build (commit b719a7f), build <local dev build> built on 2022-09-29 13:55:16 UTC
SOURCE is missing
```

**Comment by leoheck** [comment]
Other flags are not working as well

```
~/Applications …
➜ ./appimagetool-x86_64.AppImage --self-update
Option parsing failed: Unknown option --self-update
```

**Comment by leoheck** [comment]
Ah, wait, there are 2 tools? REally? Why? Why not only one tool?

**Comment by TheAssassin** [comment]
Mainly because one is a UI tool, while the other one does not depend on a desktop environment. The latter is also much more compact.
