### ISSUE TITLE
Unclear downloads in the release page, and no information in the readme

### ISSUE THREAD

**Issue by DuendeInexistente** [AppImageCommunity/AppImageUpdate#225]
So the releases page has appimageupdate, appimageupdattool, and validate.appimage, and I can't find any information on what's what there or in the readme.

**Comment by probonopd** [comment]
* `AppImageUpdate`: The GUI application
* `appimageupdatetool`: A command line tool that does the same but in the terminal
* `validate`: A tool to check signed AppImages (AppImageUpdate has this built in)
