### ISSUE TITLE
double click closes the file-chooser

### ISSUE THREAD

**Issue by max-321** [AppImageCommunity/AppImageUpdate#227]
Starting  AppImageUpdate shows me the filechooser
— if I choose a file and click on "open", it updates the file and leaves the file-chooser open, I can choose another appimage
— but, if I double-click on a file, it updates it and closes the file-chooser, so I have to restart AppImageUpdate for the next update

Expected : double-click on a file in the file-chooser lives the latter open for a new choice.

**Comment by probonopd** [comment]
Double clicking a file in a file chooser always selects that file and closes the chooser. To select multiple things, you usually need to use shift or control (not sure whether this is implemented in AppImageUpdate so far though).
